# Generated by Django 6.0.1 on 2026-01-13 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '⏳ Onay Bekliyor'), ('approved', '✅ Sipariş Verildi (Shein)'), ('dubai', '🇦🇪 Dubai Deposunda'), ('shipping', '🚚 Irak Yolunda'), ('arrived', '🏢 Erbil Şubede'), ('delivered', '📦 Teslim Edildi'), ('cancelled', '❌ İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('tracking_note', models.TextField(blank=True, null=True, verbose_name='Takip Notu (Örn: Tahmini varış 15 Mart)')),
                ('total_price_iqd', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Toplam Tutar (IQD)')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='Sepet Ekran Görüntüsü')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_link', models.URLField(max_length=1000, verbose_name='Shein Linki')),
                ('manual_price_usd', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Müşterinin Girdiği Fiyat ($)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('dalin_points', models.IntegerField(default=0, verbose_name='Dalin Puanları')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
