# Generated by Django 6.0.1 on 2026-01-13 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='Cart Screenshot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending Approval'), ('approved', '✅ Order Placed (Shein)'), ('dubai', '🇦🇪 Arrived in Dubai'), ('shipping', '🚚 On the way to Iraq'), ('arrived', '🏢 In Erbil Branch'), ('delivered', '📦 Delivered'), ('cancelled', '❌ Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_iqd',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total Price (IQD)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_note',
            field=models.TextField(blank=True, null=True, verbose_name='Tracking Note (e.g., Est. Arrival: March 15)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='manual_price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price on Screenshot ($)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_link',
            field=models.URLField(max_length=1000, verbose_name='Shein Link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dalin_points',
            field=models.IntegerField(default=0, verbose_name='Dalin Points'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
