# Generated by Django 6.0.1 on 2026-01-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_created_at_alter_order_screenshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Product Name')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Product Image')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price ($)')),
                ('shein_link', models.URLField(max_length=1000, verbose_name='Shein Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on Homepage?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
