# Generated by Django 6.0.1 on 2026-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for Cancellation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending Approval'), ('approved', '✅ Order Placed (Shein)'), ('dubai', '🇦🇪 Arrived in Dubai'), ('shipping', '🚚 On the way to Iraq'), ('arrived', '🏢 In Erbil Branch'), ('delivered', '📦 Delivered'), ('cancel_requested', '⚠️ Cancellation Requested'), ('cancelled', '❌ Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
