# Generated by Django 6.0.1 on 2026-01-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_cancel_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Discount Amount (IQD)'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_added_to_profile',
            field=models.BooleanField(default=False, verbose_name='Points Loaded?'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_spent',
            field=models.IntegerField(default=0, verbose_name='Points Used'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_to_earn',
            field=models.IntegerField(default=0, verbose_name='Points to Earn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_iqd',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Final Price (IQD)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_note',
            field=models.TextField(blank=True, null=True, verbose_name='Tracking Note'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='manual_price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price ($)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
    ]
