# Generated by Django 6.0.1 on 2026-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_discount_amount_order_points_added_to_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wants_to_use_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', '📝 Draft (Not Confirmed)'), ('pending', '⏳ Pending Approval'), ('approved', '✅ Order Placed (Shein)'), ('dubai', '🇦🇪 Arrived in Dubai'), ('shipping', '🚚 On the way to Iraq'), ('arrived', '🏢 In Erbil Branch'), ('delivered', '📦 Delivered'), ('cancel_requested', '⚠️ Cancellation Requested'), ('cancelled', '❌ Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
