# Generated by Django 6.0.1 on 2026-01-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_wants_to_use_points_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='screenshot',
        ),
        migrations.CreateModel(
            name='OrderScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='store.order')),
            ],
        ),
    ]
