# Generated by Django 6.0.1 on 2026-01-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_screenshot_orderscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Shein'e kupon sonrası ödenen gerçek tutar.", max_digits=10, null=True, verbose_name='Real Cost ($)'),
        ),
    ]
